### ISSUE TITLE
Python traceback while clicking on the icon

### ISSUE THREAD

**Issue by Gustry** [enricofer/go2mapillary#14]
Hi, I have an issue on both QGIS 3.2 and QGIS 3.3:
As soon as I click on the mapillary icon:
![screenshot from 2018-07-05 07-47-47](https://user-images.githubusercontent.com/1609292/42321655-bfdfa722-8027-11e8-801a-fd86e0eef2a9.png)

Stacktrace:
```
An error has occurred while executing Python code: 

TypeError: 'method' object is not connected 
Traceback (most recent call last):
  File "/home/trimaille/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/mapillary_explorer.py", line 373, in run
    self.canvas.extentsChanged.disconnect(self.mapChanged)
TypeError: 'method' object is not connected


Python version: 3.6.5 (default, Apr  1 2018, 05:46:30) [GCC 7.3.0] 
QGIS version: 3.2.0-Bonn Bonn, bc43194061 

Python Path:
/home/trimaille/dev/qgis/build-qgis-3_2/output/python
/home/trimaille/.local/share/QGIS/QGIS3/profiles/default/python
/home/trimaille/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/home/trimaille/dev/qgis/build-qgis-3_2/output/python/plugins
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/home/trimaille/.local/share/QGIS/QGIS3/profiles/default/python
/home/trimaille/.local/share/QGIS/QGIS3/profiles/default/python/plugins/inasafe
/home/trimaille/.local/share/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe_extras/parameters
/home/trimaille/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/home/trimaille/.local/share/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe_extras
/usr/lib/python3/dist-packages/IPython/extensions
/home/trimaille/.local/share/QGIS/QGIS3/profiles/default/python/plugins/vector_tiles_reader/ext-libs
/home/trimaille/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary
/home/trimaille/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/extlibs
/home/trimaille/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary
/home/trimaille/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary
/home/trimaille/Desktop/soufriere
```

In my logs:
```
2018-07-05T07:45:54     INFO    go2mapillary : loading vector tile [5385,7451,14]
2018-07-05T07:45:54     WARNING    Python error : An error has occurred while executing Python code: See message log (Python Error) for more details.
2018-07-05T07:47:45     WARNING    Python error : An error has occurred while executing Python code: See message log (Python Error) for more details.
```

```2018-07-05T07:45:54     WARNING    Traceback (most recent call last):
              File "/home/trimaille/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/mapillary_explorer.py", line 362, in run
              self.mapRefreshed(force=True)
              File "/home/trimaille/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/mapillary_explorer.py", line 338, in mapRefreshed
              enabledLevels = self.coverage.update_coverage(force=force)
              File "/home/trimaille/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/mapillary_coverage.py", line 350, in update_coverage
              self.download_tiles(force=force)
              File "/home/trimaille/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/mapillary_coverage.py", line 273, in download_tiles
              json_data = mapbox_vector_tile.decode(mvt, quantize_bounds=tile_box)
             TypeError: decode() got an unexpected keyword argument 'quantize_bounds'
             
2018-07-05T07:47:45     WARNING    Traceback (most recent call last):
              File "/home/trimaille/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/mapillary_explorer.py", line 373, in run
              self.canvas.extentsChanged.disconnect(self.mapChanged)
             TypeError: 'method' object is not connected
```

```
2018-07-05T07:43:33     INFO    CACHE_DIR/tmp/go2mapillary
2018-07-05T07:43:57     INFO    CACHE_DIR/tmp/go2mapillary
2018-07-05T07:45:45     INFO    CACHE_DIR/tmp/go2mapillary
2018-07-05T07:45:54     INFO    CACHE [5385,7451,14]
```

Thanks for your help

**Comment by enricofer** [comment]
No issues with the same platform here.
I see that you have _..../vector_tiles_reader/ext-libs_ in your paths. So I fear that there is some python modules adressing mismatch. Could you try to remove (not simply unload) vector_tiles_reader plugin and restart QGIS to check for embedded libraries incompatibilities ?

**Comment by Gustry** [comment]
I removed the folder `vector_tiles_reader`. Indeed it's working now. Is there a conflict in paths? Which plugin is guilty? ;-)

**Comment by enricofer** [comment]
vector_tiles_reader plugin is a more generic tool. Perhaphs it's better to rename the modules in go2mapillary to prevent these unwanted conflicts

**Comment by enricofer** [comment]
https://github.com/enricofer/go2mapillary/commit/c66bb567b3f229131d4c6a073696dea732753744

**Comment by enricofer** [comment]
and https://github.com/enricofer/go2mapillary/commit/da90bf3363b0a6453352915c45bdc9eb6818da18

**Comment by enricofer** [comment]
https://github.com/enricofer/go2mapillary/commit/8467409b64c40c5a122b5e5a1767f6c5fd56433b
