### ISSUE TITLE
problem installing plugin on qgis3 on Mac

### ISSUE THREAD

**Issue by bhattvihang** [enricofer/go2mapillary#25]
I am trying to install this plugin on my mac. However, it crashes with following error message

Couldn't load plugin 'go2mapillary' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'past' 
Traceback (most recent call last):
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/vihang/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/__init__.py", line 49, in classFactory
    from .mapillary_explorer import go2mapillary
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/vihang/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/mapillary_explorer.py", line 54, in 
    from .mapillary_coverage import mapillary_coverage, LAYER_LEVELS
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/vihang/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/mapillary_coverage.py", line 26, in 
    from go2mapillary.extlibs import mapbox_vector_tile
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/vihang/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/extlibs/mapbox_vector_tile/__init__.py", line 1, in 
    from . import encoder
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/vihang/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/extlibs/mapbox_vector_tile/encoder.py", line 3, in 
    from past.builtins import long
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'past'

Python version: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 05:52:31) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] 
QGIS version: 3.4.3-Madeira Madeira, exported 

Python Path:
/Applications/QGIS3.app/Contents/MacOS/../Resources/python
/Users/vihang/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/vihang/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/SQLite3.framework/Versions/D/Python/3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
/Users/vihang/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/vihang/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/HCMGIS/forms
/Users/vihang/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary
/Users/vihang/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/extlibs
/Users/vihang/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary
/Users/vihang/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary
/Users/vihang/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary
/Users/vihang/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary-master
/Users/vihang/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary-master/extlibs
/Users/vihang/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary-master
/Users/vihang/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2streetview
/Users/vihang/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2streetview/res
/Users/vihang/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary

Please advise what to do

**Comment by enricofer** [comment]
https://github.com/enricofer/go2mapillary/issues/15
