### ISSUE TITLE
Current image info is not working!

### ISSUE THREAD

**Issue by ahmouda12** [enricofer/go2mapillary#27]
When trying to get an image info from the image menu icon in QGIS, it gets the following error:

An error has occurred while executing Python code: 

AttributeError: 'mapillaryImageInfo' object has no attribute 'label_sequence_key' 
Traceback (most recent call last):
  File "/Users/ahmedahmouda/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/mapillary_explorer.py", line 324, in viewerConnection
    mapillaryImageInfo.openKey(self,message["key"])
  File "/Users/ahmedahmouda/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/mapillary_image_info.py", line 89, in openKey
    dialog.setup(key)
  File "/Users/ahmedahmouda/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/mapillary_image_info.py", line 68, in setup
    getattr(self, 'label_' + prop).show()
AttributeError: 'mapillaryImageInfo' object has no attribute 'label_sequence_key'

**Comment by enricofer** [comment]
Fixed in master: https://github.com/enricofer/go2mapillary/commit/4a8bfe6c4c10ce14f4be5f2f9f1af4d83750b813
I will include it in a next realease with other fixes and improvements.
Thanks for submission.
