### ISSUE TITLE
Uncaught KeyError: 'go2mapillary'


### ISSUE THREAD

**Issue by HDavisGIS** [enricofer/go2mapillary#33]
Error while unloading plugin go2mapillary
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS 3.8/apps/qgis/./python\qgis\utils.py", line 437, in unloadPlugin
    _unloadPluginModules(packageName)
  File "C:/PROGRA~1/QGIS 3.8/apps/qgis/./python\qgis\utils.py", line 466, in _unloadPluginModules
    for path in sys.modules[mod].__path__:
  File "<frozen importlib._bootstrap_external>", line 1115, in __iter__
  File "<frozen importlib._bootstrap_external>", line 1103, in _recalculate
  File "<frozen importlib._bootstrap_external>", line 1099, in _get_parent_path
KeyError: 'go2mapillary'

```
go2mapillary 2.3, QGIS 3.8.1-Zanzibar on Windows 10

**Comment by enricofer** [comment]
I don't understand what you mean with 1 2 3 steps
Could you better describe the operating steps to reproduce the issue?
Does it happen everytime you load and unload the plugin?
Does it happen after you install 3.8.1 or even previous releases are
affected?

Il mer 31 lug 2019, 16:00 Hannah Davis <notifications@github.com> ha
scritto:
